<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/08/15 15:50:04

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => 'patobica',
  'name' => 'doctrine',
)),);
